//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevOps_iConfigurator
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevOps_Questions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DevOps_Questions()
        {
            this.Questions_Options = new HashSet<Questions_Options>();
        }
    
        public int QID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public string Questions { get; set; }
    
        public virtual Section Section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Questions_Options> Questions_Options { get; set; }
    }
}
