//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevOps_iConfigurator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions_Options
    {
        public int OID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public string Options { get; set; }
        public Nullable<int> NextQID { get; set; }
    
        public virtual DevOps_Questions DevOps_Questions { get; set; }
    }
}
